Number1 = input("What is number 1? ")
Number2 = input("What is number 2? ")
print("Number 1: " + Number1)
print("Number 2: " + Number2)
print(Number1 + "+" + Number2 + "=" + str(int(Number1) + int(Number2)))
print(Number1 + "-" + Number2 + "=" + str(int(Number1) - int(Number2)))
print(Number1 + "*" + Number2 + "=" + str(int(Number1) * int(Number2)))
print(Number1 + "/" + Number2 + "=" + str(int(Number1) / int(Number2)))